<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="base_radius" value="0.16"/>
    <xacro:property name="base_height" value="0.10"/>
    <xacro:property name="wheel_radius" value="0.045"/>
    <xacro:property name="wheel_width" value="0.025"/>
    <xacro:property name="wheel_offset_y" value="0.14"/>
    <xacro:property name="base_elevation" value="0.015"/>

    <xacro:macro name="mobile_base" params="parent_link">
        
        <link name="chassis_main">
            <visual>
                <origin xyz="0 0 ${base_height*0.2}"/>
                <geometry><cylinder radius="${base_radius}" length="${base_height*0.4}"/></geometry>
                <material name="tire_black"/>
            </visual>
            <visual>
                <origin xyz="0 0 ${base_height*0.6}"/>
                <geometry><cylinder radius="${base_radius * 0.95}" length="${base_height*0.4}"/></geometry>
                <material name="dark_grey"/>
            </visual>
            <visual>
                <origin xyz="0 0 ${base_height - 0.002}"/>
                <geometry><cylinder radius="${base_radius * 0.92}" length="0.005"/></geometry>
                <material name="industrial_orange"/>
            </visual>
            <visual>
                <origin xyz="${base_radius-0.02} 0 ${base_height/2}"/>
                <geometry><box size="0.02 0.12 0.02"/></geometry>
                <material name="emission_blue"/>
            </visual>
            
            <collision>
                <origin xyz="0 0 ${base_height/2}"/>
                <geometry><cylinder radius="${base_radius}" length="${base_height}"/></geometry>
            </collision>
            
            <xacro:cylinder_inertia m="5.0" r="${base_radius}" h="${base_height}"/>
        </link>

        <joint name="base_joint" type="fixed">
            <parent link="${parent_link}"/>
            <child link="chassis_main"/>
            <origin xyz="0 0 ${wheel_radius + base_elevation - base_height/2}" rpy="0 0 0"/>
        </joint>

        <gazebo reference="chassis_main">
            <material>Gazebo/DarkGrey</material>
        </gazebo>

        <xacro:macro name="drive_wheel" params="prefix reflect">
            <link name="${prefix}_wheel_link">
                <visual>
                    <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
                    <material name="tire_black"/>
                </visual>
                <visual>
                    <geometry><cylinder radius="${wheel_radius * 0.6}" length="${wheel_width + 0.002}"/></geometry>
                    <material name="brushed_aluminum"/>
                </visual>
                <collision>
                    <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
                </collision>
                <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" h="${wheel_width}"/>
            </link>

            <joint name="${prefix}_wheel_joint" type="continuous">
                <parent link="chassis_main"/>
                <child link="${prefix}_wheel_link"/>
                <origin xyz="0 ${reflect * wheel_offset_y} ${base_height/2 - base_elevation}" rpy="-1.5707 0 0"/>
                <axis xyz="0 0 1"/>
            </joint>

            <gazebo reference="${prefix}_wheel_link">
                <material>Gazebo/FlatBlack</material>
                <mu1>1.0</mu1> <mu2>1.0</mu2>
            </gazebo>
        </xacro:macro>

        <xacro:drive_wheel prefix="left" reflect="1"/>
        <xacro:drive_wheel prefix="right" reflect="-1"/>

        <xacro:macro name="caster_wheel" params="prefix x_offset">
            <link name="${prefix}_caster_link">
                <visual>
                    <geometry><sphere radius="${wheel_radius*0.6}"/></geometry>
                    <material name="tire_black"/>
                </visual>
                <collision>
                    <geometry><sphere radius="${wheel_radius*0.6}"/></geometry>
                </collision>
                <xacro:sphere_inertia m="0.1" r="${wheel_radius*0.6}"/>
            </link>
            
            <joint name="${prefix}_caster_joint" type="fixed">
                <parent link="chassis_main"/>
                <child link="${prefix}_caster_link"/>
                <origin xyz="${x_offset} 0 ${base_height/2 - base_elevation + (wheel_radius*0.6 - wheel_radius)}" rpy="0 0 0"/>
            </joint>
            
            <gazebo reference="${prefix}_caster_link">
                <material>Gazebo/DarkGrey</material>
                <mu1>0.001</mu1>
                <mu2>0.001</mu2>
            </gazebo>
        </xacro:macro>

        <xacro:caster_wheel prefix="front" x_offset="${base_radius - 0.05}"/>
        <xacro:caster_wheel prefix="rear" x_offset="${-base_radius + 0.05}"/>

    </xacro:macro>
</robot>