<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="sensor_stack" params="parent_link chassis_height">

        <link name="lidar_link">
            <visual>
                <origin xyz="0 0 0"/>
                <geometry><cylinder radius="0.04" length="0.02"/></geometry>
                <material name="dark_grey"/>
            </visual>
            <visual>
                <origin xyz="0 0 0.02"/>
                <geometry><cylinder radius="0.038" length="0.025"/></geometry>
                <material name="sensor_black"/>
            </visual>
            <collision>
                <origin xyz="0 0 0.015"/>
                <geometry><cylinder radius="0.04" length="0.05"/></geometry>
            </collision>
            <xacro:cylinder_inertia m="0.2" r="0.04" h="0.05"/>
        </link>

        <joint name="lidar_joint" type="fixed">
            <parent link="${parent_link}"/>
            <child link="lidar_link"/>
            <origin xyz="0.05 0 ${chassis_height}" rpy="0 0 0"/>
        </joint>

        <gazebo reference="lidar_link">
            <material>Gazebo/FlatBlack</material>
            <sensor name='lidar' type='gpu_lidar'>
                <pose relative_to='lidar_link'>0 0 0.03 0 0 0</pose>
                <topic>/scan</topic>
                <update_rate>10</update_rate>
                <frame_id>lidar_link</frame_id>
                <gz_frame_id>lidar_link</gz_frame_id> 
                <ray>
                    <scan><horizontal><samples>360</samples><resolution>1</resolution><min_angle>-3.14</min_angle><max_angle>3.14</max_angle></horizontal></scan>
                    <range><min>0.10</min><max>12.0</max><resolution>0.01</resolution></range>
                    <noise><type>gaussian</type><mean>0.0</mean><stddev>0.01</stddev></noise>
                </ray>
                <always_on>1</always_on><visualize>true</visualize>
            </sensor>
        </gazebo>

        <link name="camera_link">
            <visual>
                <geometry><box size="0.02 0.06 0.02"/></geometry>
                <material name="sensor_black"/>
            </visual>
            <visual>
                <origin xyz="0.01 0 0" rpy="0 1.57 0"/>
                <geometry><cylinder radius="0.008" length="0.005"/></geometry>
                <material name="lens_blue"/>
            </visual>
            <collision>
                <geometry><box size="0.02 0.06 0.02"/></geometry>
            </collision>
            <xacro:box_inertia m="0.05" x="0.02" y="0.06" z="0.02"/>
        </link>

        <joint name="camera_joint" type="fixed">
            <parent link="${parent_link}"/>
            <child link="camera_link"/>
            <origin xyz="0.12 0 ${chassis_height + 0.05}" rpy="0 0 0"/>
        </joint>
        
        <gazebo reference="camera_link">
            <material>Gazebo/FlatBlack</material>
            
            <sensor name="camera_rgb" type="camera">
                <pose relative_to="camera_link">0.01 0 0 0 0 0</pose>
                <always_on>1</always_on>
                <update_rate>10</update_rate>
                <topic>/camera/image</topic> <frame_id>camera_link</frame_id>
                <gz_frame_id>camera_link</gz_frame_id>
                <camera>
                    <horizontal_fov>1.2</horizontal_fov>
                    <image><width>640</width><height>480</height><format>R8G8B8</format></image>
                    <clip><near>0.05</near><far>10.0</far></clip>
                </camera>
            </sensor>

            <sensor name="camera_depth" type="depth_camera">
                <pose relative_to="camera_link">0.01 0 0 0 0 0</pose>
                <always_on>1</always_on>
                <update_rate>10</update_rate>
                <topic>/camera/depth_image</topic> <frame_id>camera_link</frame_id>
                <gz_frame_id>camera_link</gz_frame_id>
                <camera>
                    <horizontal_fov>1.2</horizontal_fov>
                    <image><width>640</width><height>480</height><format>R_FLOAT32</format></image>
                    <clip><near>0.05</near><far>10.0</far></clip>
                </camera>
            </sensor>
        </gazebo>

        <link name="imu_link">
            <visual><geometry><box size="0.01 0.01 0.01"/></geometry><material name="industrial_orange"/></visual>
            <inertial><mass value="0.01"/><inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/></inertial>
        </link>
        <joint name="imu_joint" type="fixed">
            <parent link="${parent_link}"/>
            <child link="imu_link"/><origin xyz="0 0 0.05"/>
        </joint>
         <gazebo reference="imu_link">
            <sensor name="imu" type="imu">
                <frame_id>imu_link</frame_id>
                <gz_frame_id>imu_link</gz_frame_id>
                <always_on>1</always_on><update_rate>100</update_rate><topic>/imu</topic>
                <imu>
                    <angular_velocity>
                        <x><noise type="gaussian"><mean>0.0</mean><stddev>2e-4</stddev></noise></x>
                        <y><noise type="gaussian"><mean>0.0</mean><stddev>2e-4</stddev></noise></y>
                        <z><noise type="gaussian"><mean>0.0</mean><stddev>2e-4</stddev></noise></z>
                    </angular_velocity>
                    <linear_acceleration>
                        <x><noise type="gaussian"><mean>0.0</mean><stddev>1.7e-2</stddev></noise></x>
                        <y><noise type="gaussian"><mean>0.0</mean><stddev>1.7e-2</stddev></noise></y>
                        <z><noise type="gaussian"><mean>0.0</mean><stddev>1.7e-2</stddev></noise></z>
                    </linear_acceleration>
                </imu>
            </sensor>
        </gazebo>

    </xacro:macro>
</robot>